@startuml 分析类图

skinparam boundary {
  BackgroundColor tomato
}

skinparam control {
  BackgroundColor lightgreen
}

skinparam entity {
  BackgroundColor lightblue
}

boundary boundary_1

control control_1
control control_1_1
control control_1_2

entity entity_1

' relations
control_1 <|-- control_1_1
control_1 <|-- control_1_2

control_1 "1" *- "1..n" entity_1

boundary_1 -> control_1

@enduml